/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomTextInput {
    }
}
declare global {
    interface HTMLCustomTextInputElement extends Components.CustomTextInput, HTMLStencilElement {
    }
    var HTMLCustomTextInputElement: {
        prototype: HTMLCustomTextInputElement;
        new (): HTMLCustomTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "custom-text-input": HTMLCustomTextInputElement;
    }
}
declare namespace LocalJSX {
    interface CustomTextInput {
    }
    interface IntrinsicElements {
        "custom-text-input": CustomTextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-text-input": LocalJSX.CustomTextInput & JSXBase.HTMLAttributes<HTMLCustomTextInputElement>;
        }
    }
}
